import { Component, OnInit, computed, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { ApiService } from '../core/api.service';
import { CASES, DOCTORS, SERVICES } from '../core/data';
import { Review } from '../core/models';
import { RevealDirective } from '../shared/reveal.directive';
import { BeforeAfterComponent } from '../shared/before-after.component';
import { DoctorCardComponent, ReviewCardComponent, ServiceCardComponent } from '../shared/cards';

@Component({
  selector: 'app-home', standalone: true,
  imports: [RouterLink, RevealDirective, BeforeAfterComponent, DoctorCardComponent, ReviewCardComponent, ServiceCardComponent],
  template: `
<header class="relative flex min-h-[100svh] items-center overflow-hidden bg-hero-glow pb-16 pt-32 text-pearl max-lg:min-h-0 max-lg:pb-12 max-lg:pt-28 max-sm:pb-10 max-sm:pt-24"><div class="container"><div class="grid items-center gap-x-6 gap-y-10 md:gap-x-12 lg:grid-cols-12 lg:gap-y-12"><div class="max-lg:text-center lg:col-span-7">
<div class="mb-[1.4rem] inline-flex flex-wrap items-center justify-center gap-[.6rem] rounded-[50px] border border-[rgba(235,208,142,.4)] bg-[rgba(250,251,255,.08)] px-4 py-[.4rem] text-center text-[.9rem]"><span class="whitespace-nowrap tracking-[2px] text-gold"><i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i></span><span><b>{{ avg() }}</b> from our patients</span></div>
<h1 class="text-[clamp(2.3rem,7vw,5.6rem)]">A smile is drawn, <em class="text-gold2">never rushed.</em></h1><p class="my-6 max-w-[34rem] text-[1.25rem] font-light text-[rgba(250,251,255,.78)] max-lg:mx-auto">Aurum is a private dental atelier where every treatment is planned like a commission: unhurried, painless and finished by hand.</p>
<a routerLink="/book" class="btn-gold mb-2 mr-2 max-sm:mr-0 max-sm:block max-sm:w-full">Reserve your consultation</a><a routerLink="/results" class="btn-line mb-2 max-sm:block max-sm:w-full">See real results</a>
<div class="-mx-3 mt-12 grid grid-cols-3 border-t border-[rgba(250,251,255,.15)] pt-6 max-sm:mt-8"><div class="px-3"><b class="block font-serif text-[2.2rem] leading-none text-gold2 max-sm:text-[1.7rem]">12k+</b><small class="text-[rgba(250,251,255,.65)] max-sm:block max-sm:text-[.78rem] max-sm:leading-[1.3]">smiles finished</small></div><div class="px-3"><b class="block font-serif text-[2.2rem] leading-none text-gold2 max-sm:text-[1.7rem]">18</b><small class="text-[rgba(250,251,255,.65)] max-sm:block max-sm:text-[.78rem] max-sm:leading-[1.3]">years of practice</small></div><div class="px-3"><b class="block font-serif text-[2.2rem] leading-none text-gold2 max-sm:text-[1.7rem]">3</b><small class="text-[rgba(250,251,255,.65)] max-sm:block max-sm:text-[.78rem] max-sm:leading-[1.3]">specialist dentists</small></div></div></div>
<div class="lg:col-span-5"><div class="relative grid place-items-center before:absolute before:aspect-square before:w-[88%] before:animate-spin-slow before:rounded-full before:border before:border-dashed before:border-[rgba(235,208,142,.3)] before:content-[''] max-lg:mx-auto max-lg:mt-6 max-lg:max-w-[380px]"><svg class="w-[min(360px,80%)] align-middle drop-shadow-[0_20px_50px_rgba(120,170,255,.35)] max-lg:w-[min(300px,62%)]" viewBox="0 0 200 200" role="img" aria-label="Tooth outline drawing itself"><path class="animate-tooth [fill:rgba(250,251,255,0)] [stroke-dasharray:900] [stroke-dashoffset:900] [stroke-width:1.6] stroke-gold2 motion-reduce:[fill:rgba(250,251,255,.95)] motion-reduce:[stroke-dashoffset:0]" d="M100 22C72 6 30 20 35 66C38 96 50 110 55 150C58 176 68 190 78 170C88 150 92 126 100 126C108 126 112 150 122 170C132 190 142 176 145 150C150 110 162 96 165 66C170 20 128 6 100 22Z"/><path class="animate-tooth [fill:rgba(250,251,255,0)] [stroke-dasharray:900] [stroke-dashoffset:900] [stroke-width:1.6] stroke-gold2 motion-reduce:[fill:rgba(250,251,255,.95)] motion-reduce:[stroke-dashoffset:0] opacity-0" d="M160 30l3 9 9 3-9 3-3 9-3-9-9-3 9-3z"/><path class="animate-tooth [fill:rgba(250,251,255,0)] [stroke-dasharray:900] [stroke-dashoffset:900] [stroke-width:1.6] stroke-gold2 motion-reduce:[fill:rgba(250,251,255,.95)] motion-reduce:[stroke-dashoffset:0] opacity-0 [animation-delay:4s]" d="M38 110l2 6 6 2-6 2-2 6-2-6-6-2 6-2z"/></svg></div></div></div></div></header>

<section class="py-[clamp(3.2rem,8vw,6rem)]"><div class="container"><div class="mx-auto mb-[clamp(2rem,5vw,3.5rem)] max-w-[40rem] text-center" appReveal><i class="bi bi-gem text-[1.6rem] text-gold"></i><h2>Why patients choose Aurum</h2><p class="mt-4">Four promises we keep at every visit.</p></div><div class="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
<div appReveal><div class="group relative h-full overflow-hidden rounded-[26px] border border-sky bg-card-fade px-[1.6rem] py-8 text-center transition-[transform,box-shadow] duration-[.4s] before:absolute before:inset-x-0 before:top-0 before:h-1 before:origin-center before:scale-x-0 before:bg-bar-line before:transition-transform before:duration-500 before:content-[''] hover:-translate-y-2 hover:shadow-lift-why hover:before:scale-x-100 max-md:px-[1.2rem] max-md:py-[1.6rem]"><div class="mx-auto mb-[1.2rem] grid h-[72px] w-[72px] place-items-center rounded-full bg-orb-ink text-[1.8rem] text-gold2 shadow-[0_0_0_6px_#DCE9FF] transition-transform duration-[.6s] group-hover:[transform:rotateY(360deg)]"><i class="bi bi-gem"></i></div><h3>Hand-finished porcelain</h3><p class="mb-0">Every veneer and crown is shaded to match you.</p></div></div>
<div appReveal><div class="group relative h-full overflow-hidden rounded-[26px] border border-sky bg-card-fade px-[1.6rem] py-8 text-center transition-[transform,box-shadow] duration-[.4s] before:absolute before:inset-x-0 before:top-0 before:h-1 before:origin-center before:scale-x-0 before:bg-bar-line before:transition-transform before:duration-500 before:content-[''] hover:-translate-y-2 hover:shadow-lift-why hover:before:scale-x-100 max-md:px-[1.2rem] max-md:py-[1.6rem]"><div class="mx-auto mb-[1.2rem] grid h-[72px] w-[72px] place-items-center rounded-full bg-orb-ink text-[1.8rem] text-gold2 shadow-[0_0_0_6px_#DCE9FF] transition-transform duration-[.6s] group-hover:[transform:rotateY(360deg)]"><i class="bi bi-shield-check"></i></div><h3>Painless by design</h3><p class="mb-0">Gentle anaesthesia and calm, unhurried hands.</p></div></div>
<div appReveal><div class="group relative h-full overflow-hidden rounded-[26px] border border-sky bg-card-fade px-[1.6rem] py-8 text-center transition-[transform,box-shadow] duration-[.4s] before:absolute before:inset-x-0 before:top-0 before:h-1 before:origin-center before:scale-x-0 before:bg-bar-line before:transition-transform before:duration-500 before:content-[''] hover:-translate-y-2 hover:shadow-lift-why hover:before:scale-x-100 max-md:px-[1.2rem] max-md:py-[1.6rem]"><div class="mx-auto mb-[1.2rem] grid h-[72px] w-[72px] place-items-center rounded-full bg-orb-ink text-[1.8rem] text-gold2 shadow-[0_0_0_6px_#DCE9FF] transition-transform duration-[.6s] group-hover:[transform:rotateY(360deg)]"><i class="bi bi-clock-history"></i></div><h3>Unhurried visits</h3><p class="mb-0">Long appointments, so nothing is ever rushed.</p></div></div>
<div appReveal><div class="group relative h-full overflow-hidden rounded-[26px] border border-sky bg-card-fade px-[1.6rem] py-8 text-center transition-[transform,box-shadow] duration-[.4s] before:absolute before:inset-x-0 before:top-0 before:h-1 before:origin-center before:scale-x-0 before:bg-bar-line before:transition-transform before:duration-500 before:content-[''] hover:-translate-y-2 hover:shadow-lift-why hover:before:scale-x-100 max-md:px-[1.2rem] max-md:py-[1.6rem]"><div class="mx-auto mb-[1.2rem] grid h-[72px] w-[72px] place-items-center rounded-full bg-orb-ink text-[1.8rem] text-gold2 shadow-[0_0_0_6px_#DCE9FF] transition-transform duration-[.6s] group-hover:[transform:rotateY(360deg)]"><i class="bi bi-patch-check"></i></div><h3>Clear pricing</h3><p class="mb-0">You see the full plan and cost before we begin.</p></div></div></div></div></section>

<section class="pb-[clamp(3.2rem,8vw,6rem)] pt-0"><div class="container"><div class="mx-auto mb-[clamp(2rem,5vw,3.5rem)] max-w-[40rem] text-center" appReveal><i class="bi bi-heart-pulse text-[1.6rem] text-gold"></i><h2>Treatments, made to measure</h2><p class="mt-4">Each plan starts with a 3D scan and a conversation.</p></div>
<div class="grid gap-6 md:grid-cols-2 lg:grid-cols-3">@for (s of services; track s.name) {<div appReveal><app-service-card [s]="s" /></div>}</div>
<div class="mt-12 text-center"><a routerLink="/treatments" class="btn-gold">All treatments</a></div></div></section>

<section class="pb-[clamp(3.2rem,8vw,6rem)] pt-0"><div class="container"><div class="rounded-[40px] bg-band-ink px-8 py-16 text-pearl max-md:rounded-[26px] max-md:px-4 max-md:py-[2.4rem]"><div class="grid gap-6 text-center sm:grid-cols-3"><div appReveal><div class="font-serif text-[3.4rem] leading-none text-gold2 max-md:text-[2.6rem]">60 min</div><small>minimum per visit</small></div><div appReveal><div class="font-serif text-[3.4rem] leading-none text-gold2 max-md:text-[2.6rem]">3D</div><small>scan and smile preview</small></div><div appReveal><div class="font-serif text-[3.4rem] leading-none text-gold2 max-md:text-[2.6rem]">0</div><small>hidden charges</small></div></div></div></div></section>

<section class="pb-[clamp(3.2rem,8vw,6rem)] pt-0"><div class="container"><div class="mx-auto mb-[clamp(2rem,5vw,3.5rem)] max-w-[40rem] text-center" appReveal><i class="bi bi-person-hearts text-[1.6rem] text-gold"></i><h2>The hands behind your smile</h2><p class="mt-4">Meet the dentists who will care for you.</p></div>
<div class="grid gap-6 md:grid-cols-2 lg:grid-cols-3">@for (d of doctors; track d.name) {<div appReveal><app-doctor-card [d]="d" /></div>}</div></div></section>

<section class="pb-[clamp(3.2rem,8vw,6rem)] pt-0"><div class="container"><div class="mx-auto mb-[clamp(2rem,5vw,3.5rem)] max-w-[40rem] text-center" appReveal><i class="bi bi-arrows-expand text-[1.6rem] text-gold"></i><h2>See the difference</h2><p class="mt-4">Drag the handle to compare before and after.</p></div>
<div><div class="mx-auto lg:w-[calc((100%+1.5rem)*8/12-1.5rem)]" appReveal><app-before-after [data]="firstCase" /></div></div>
<div class="mt-12 text-center"><a routerLink="/results" class="btn-gold">More results</a></div></div></section>

<section class="pb-[clamp(3.2rem,8vw,6rem)] pt-0"><div class="container"><div class="mx-auto mb-[clamp(2rem,5vw,3.5rem)] max-w-[40rem] text-center" appReveal><i class="bi bi-chat-quote text-[1.6rem] text-gold"></i><h2>Words from our patients</h2><p class="mt-4">Real ratings from real visits.</p></div>
<div class="grid gap-6 md:grid-cols-2 lg:grid-cols-3">@for (r of top(); track r.id) {<div appReveal><app-review-card [r]="r" /></div>}</div>
<div class="mt-12 text-center"><a routerLink="/reviews" class="btn-gold">Read all reviews</a></div></div></section>

<section class="pb-[clamp(3.2rem,8vw,6rem)] pt-0"><div class="container"><div class="relative overflow-hidden rounded-[40px] bg-band-blue px-8 py-16 text-center text-white max-md:rounded-[26px] max-md:px-[1.2rem] max-md:py-[2.6rem]" appReveal><i class="bi bi-stars text-[calc(1.375rem+1.5vw)] text-gold2 xl:text-[2.5rem]"></i><h2 class="mt-2">Your smile deserves an unhurried hour.</h2><p class="my-4">Reserve a consultation and see your result before we begin.</p><a routerLink="/book" class="btn-gold">Book your visit</a></div></div></section>`,
})
export class HomeComponent implements OnInit {
  services = SERVICES; doctors = DOCTORS; firstCase = CASES[0];
  reviews = signal<Review[]>([]);
  top = computed(() => this.reviews().slice(0, 3));
  avg = computed(() => {
    const r = this.reviews();
    return r.length ? (r.reduce((a, x) => a + x.rating, 0) / r.length).toFixed(1) : '4.9';
  });
  constructor(private api: ApiService) {}
  ngOnInit(): void { this.api.reviews().subscribe({ next: r => this.reviews.set(r), error: () => this.reviews.set([]) }); }
}
